before_install:
  - sudo apt-get update -qq
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_i386.deb -O hugo.deb
  - sudo dpkg -i hugo.deb
  - sudo apt-get install python-pip -y
  - sudo pip install pygments

script: chmod +x deploy.sh && bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/morzproject/morz-project-blog.git
  - secure: "ghFoZxAv7Ek5VBmJsxB4KP1lweXK5iD3mcJK1qsTT9vNZiQuIQtxdw41pOwL9teFTftHO5SPzRLV7Xi1Ws+BUEOg/Yqzx0rCSyAWDs+CslhhUgHNjhCu0n1dnGYNYazZknrcmrsfMS2/IS1YzPOV4cNs1OyTk/Gs9LSQkrvn+1t4UUnLVImjzXfAORiHr22PnigDINwHE/bBqzIbYTct5Zai+lpfp/ICA1xKxb+HjTYAJwCVFOdY+JVe9j9vtxMYaWrTV9Jw4RqWIZDBXOrI8UsWfjKWROKk4XOC/EbzWjZoGuyr0fUt7QuDztQtBvXG9t5o791hZLslyxafixiKVQ7dF+0n0NS2zrAMEN/une+8NEStxZx4KKKsAuPaLMgtGWkphdnBdbfZJDuPwxTNAsfMsfqFZLdnE5bC+K/UCH90C4Xe728wGZxwP76XEMFml9sza+4vCE6J1xGnugrO16Fem/c6xI7L4E26jFlbXh2q16zWaxcV0wGcSrk4JgdtYp7Dq84EyzHGfpnWTVvz2kL8PRYEfj9+wcyEwQxlPddG5NIrPHX39dP+uItgw5KVre4AHq6DLxvdKANkwCje3jARPJJwF3Zr8BAyHpzrngZp5okeFziSFJYAiuA2bGAF8nusyFeuqmK/4sGmiIZkg0Ip+Z1nYJXI3czb6KFrVb8="
